parserOptions:
    ecmaFeatures:
      arrowFunctions: true
      binaryLiterals: false
      blockBindings: true
      classes: true
      defaultParams: true
      destructuring: true
      forOf: true
      generators: true
      modules: false
      objectLiteralComputedProperties: true
      objectLiteralDuplicateProperties: false
      objectLiteralShorthandMethods: true
      objectLiteralShorthandProperties: true
      octalLiterals: false
      regexUFlag: false
      regexYFlag: false
      restParams: true
      spread: true
      superInFunctions: true
      templateStrings: true
      unicodePointEscapes: true
      globalReturn: false
      jsx: true
env:
  browser: true
  node: true
parser: babel-eslint
plugins:
    - react
rules:
  comma-dangle:
      - 1
      - objects: always-multiline
  no-cond-assign:
      - 1
      - except-parens
  no-console: 0
  no-constant-condition: 1
  no-control-regex: 1
  no-debugger: 1
  no-dupe-args: 1
  no-dupe-keys: 1
  no-duplicate-case: 1
  no-empty-character-class: 1
  no-empty: 1
  no-ex-assign: 1
  no-extra-boolean-cast: 1
  no-extra-parens: 0
  no-extra-semi: 1
  no-func-assign: 1
  no-inner-declarations:
      - 1
      - functions
  no-invalid-regexp: 1
  no-irregular-whitespace: 1
  no-negated-in-lhs: 1
  no-obj-calls: 1
  no-regex-spaces: 1
  no-sparse-arrays: 1
  no-unexpected-multiline: 1
  no-unreachable: 1
  use-isnan: 1
  valid-jsdoc: 1
  valid-typeof: 1
  accessor-pairs: 0
  block-scoped-var: 1
  complexity: 0
  consistent-return: 1
  curly:
      - 1
      - all
  default-case: 1
  dot-location:
      - 1
      - property
  dot-notation:
      - 1
      - allowKeywords: true
        allowPattern: ''
  eqeqeq: 1
  guard-for-in: 0
  no-alert: 1
  no-caller: 1
  no-case-declarations: 0
  no-div-regex: 1
  no-else-return: 1
  no-empty-pattern: 1
  no-eq-null: 1
  no-eval: 1
  no-extend-native: 1
  no-extra-bind: 1
  no-fallthrough: 1
  no-floating-decimal: 1
  no-implicit-coercion: 1
  no-implied-eval: 1
  no-invalid-this: 0
  no-iterator: 1
  no-labels: 1
  no-lone-blocks: 1
  no-loop-func: 1
  no-magic-numbers:
      - 1
      - ignore:
        - -1
        - 0
        - 1
  no-multi-spaces: 1
  no-multi-str: 1
  no-native-reassign: 1
  no-new-func: 1
  no-new-wrappers: 1
  no-new: 1
  no-octal-escape: 1
  no-octal: 1
  no-param-reassign:
      - 1
      - props: false
  no-process-env: 0
  no-proto: 1
  no-redeclare: 1
  no-return-assign: 1
  no-script-url: 1
  no-self-compare: 1
  no-sequences: 1
  no-throw-literal: 1
  no-unused-expressions:
      - 1
      - allowShortCircuit: true
        allowTernary: true
  no-useless-call: 1
  no-useless-concat: 1
  no-void: 0
  no-with: 1
  radix: 0
  vars-on-top: 1
  wrap-iife:
      - 1
      - inside
  yoda:
      - 1
      - never
  strict:
      - 1
      - never
  init-declarations: 0
  no-catch-shadow: 1
  no-delete-var: 1
  no-label-var: 1
  no-shadow-restricted-names: 1
  no-shadow: 1
  no-undef-init: 1
  no-unused-vars:
      - 1
      - vars: local
        args: after-used
  callback-return: 1
  global-require: 1
  handle-callback-err: 1
  no-mixed-requires: 1
  no-new-require: 1
  no-path-concat: 1
  no-process-exit: 1
  no-restricted-modules:
      - 1
      - ''
  no-sync: 1
  array-bracket-spacing:
      - 1
      - never
  block-spacing:
      - 1
      - always
  brace-style:
      - 1
      - 1tbs
      - allowSingleLine: true
  camelcase:
      - 1
      - properties: always
  comma-spacing:
      - 0
      - before: false
        after: true
  comma-style:
      - 1
      - last
  computed-property-spacing: 0
  consistent-this: 0
  eol-last: 1
  func-names: 1
  func-style: 0
  id-length: 0
  id-match:
      - 0
      - "^[a-z]+([A-Z][a-z]*)*$"
      - properties: true
  indent:
      - 1
      - 4
  jsx-quotes:
      - 1
      - prefer-single
  key-spacing:
      - 1
      - beforeColon: false
        afterColon: true
  linebreak-style: 0
  lines-around-comment:
      - 1
      - beforeLineComment: false
        allowBlockStart: true
        allowObjectStart: true
        allowArrayStart: true
  max-nested-callbacks:
      - 0
      - 3
  new-cap:
      - 1
      - capIsNewExceptions:
        - NaN
        - T.Promise
  new-parens: 1
  newline-after-var: 0
  no-array-constructor: 1
  no-continue: 1
  no-lonely-if: 1
  no-mixed-spaces-and-tabs: 1
  no-multiple-empty-lines:
      - 1
      - max: 1
  no-negated-condition: 1
  no-nested-ternary: 0
  no-new-object: 1
  no-restricted-syntax:
      - 1
      - BreakStatement
      - ContinueStatement
      - DoWhileStatement
      - DebuggerStatement
      - LabeledStatement
      - WhileStatement
      - WithStatement
      - ExportAllDeclaration
      - ExportSpecifier
      - ImportNamespaceSpecifier
  no-spaced-func: 1
  no-ternary: 0
  no-trailing-spaces: 1
  no-underscore-dangle: 0
  no-unneeded-ternary: 1
  object-curly-spacing:
      - 1
      - always
  one-var:
      - 1
      - never
  operator-assignment:
      - 1
      - never
  operator-linebreak:
      - 1
      - after
  padded-blocks:
      - 0
      - never
  quote-props:
      - 0
      - as-needed
  quotes:
      - 1
      - single
      - allowTemplateLiterals: true
        avoidEscape: true
  require-jsdoc: 0
  semi-spacing:
      - 1
      - before: false
        after: true
  semi:
      - 1
      - always
  sort-vars: 0
  space-after-keywords: 0
  space-before-blocks:
      - 1
      - always
  space-before-function-paren:
      - 1
      - never
  space-before-keywords:
      - 0
      - never
  space-in-parens:
      - 1
      - never
  space-infix-ops: 1
  space-unary-ops: 0
  spaced-comment:
      - 1
      - always
  wrap-regex: 1
  arrow-body-style:
      - 1
      - as-needed
  arrow-parens:
      - 1
      - always
  arrow-spacing:
      - 1
      - before: true
        after: true
  constructor-super: 1
  generator-star-spacing:
      - 1
      - after
  no-class-assign: 1
  no-const-assign: 1
  no-dupe-class-members: 1
  no-this-before-super: 1
  no-var: 1
  object-shorthand: 1
  prefer-arrow-callback: 1
  require-yield: 1
  max-depth:
      - 0
      - 3
  max-len:
      - 1
  max-params: 0
  max-statements: 0
  no-bitwise: 1
  no-plusplus: 1
  react/display-name: 0
  react/forbid-prop-types: 0
  react/jsx-boolean-value: 1
  react/jsx-closing-bracket-location: 0
  react/jsx-curly-spacing: 0
  react/jsx-key: 1
  react/jsx-max-props-per-line: 0
  react/jsx-no-bind: 0
  react/jsx-no-duplicate-props: 1
  react/jsx-no-undef: 1
  react/jsx-pascal-case: 1
  react/jsx-sort-props:
      - 1
      - shorthandFirst: true
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/no-danger: 1
  react/no-did-mount-set-state: 1
  react/no-did-update-set-state: 1
  react/no-direct-mutation-state: 1
  react/no-multi-comp: 0
  react/no-set-state: 0
  react/no-unknown-property: 1
  react/prefer-es6-class: 1
  # react/prop-types: 1
  react/react-in-jsx-scope: 1
  react/self-closing-comp: 1
  react/wrap-multilines: 0
